Salon/Models/ViewModels/VisitViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Salon.Models
{
    public class VisitShortViewModel
    {
        [Key]
        public int visitId { get; set; }
        [Display(Name = "Datum")]
        public DateTime created { get; set; }
        [Display(Name = "Kunde")]
        public Customers customer { get; set; }
        [Display(Name = "Stylist")]
        public AspNetUsers stylist { get; set; }

    }

    public class VisitDetailViewModel
    {
        [Key]
        public int visitId { get; set; }
        [Display(Name = "Datum")]
        public DateTime created { get; set; }
        [Display(Name = "Kunde")]
        public Customers customer { get; set; }
        [Display(Name = "Stylist")]
        public AspNetUsers stylist { get; set; }
        [Display(Name = "Dauer")]
        public int duration { get; set; }
        [Display(Name = "Bearbeitet von")]
        public AspNetUsers modifiedBy { get; set; }
        [Display(Name = "Bearbeitet am")]
        public DateTime modified { get; set; }
        [Display(Name = "Behandlungen")]
        public List<VisitTreatment> treatments { get; set; }

    }

    public class VisitCreateViewModel
    {
        [Key]
        public int visitId { get; set; }
        [Display(Name = "Datum")]
        public DateTime created { get; set; }
        [Display(Name = "Kunde")]
        public Customers customer { get; set; }
        [Display(Name = "Stylist")]
        public AspNetUsers stylist { get; set; }
        [Display(Name = "mögliche Behandlungen")]
        public List<Treatments> availableTreatments { get; set; }
        [Display(Name = "ausgewählte Behandlungen")]
        public List<Treatments> selectedTreatments { get; set; }

    }

    public class VisitTreatment
    {
        [Key]
        public int treatmentID { get; set; }
        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name = "Schritte")]
        public List<VisitTasks> tasks { get; set; }

        public VisitTreatment()
        {
            this.tasks = new List<VisitTasks>();
        }
    }
}

Salon/Models/VisitViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Salon.Models {
    public class VisitShortViewModel {
        [Key]
        public int visitId { get; set; }
        [Display(Name = "Datum")]
        public DateTime created { get; set; }
        [Display(Name = "Kunde")]
        public Customers customer { get; set; }
        [Display(Name = "Stylist")]
        public AspNetUsers stylist { get; set; }

    }

    public class VisitDetailViewModel {
        [Key]
        public int visitId { get; set; }
        [Display(Name = "Datum")]
        public DateTime created { get; set; }
        [Display(Name = "Kunde")]
        public Customers customer { get; set; }
        [Display(Name = "Stylist")]
        public AspNetUsers stylist { get; set; }
        [Display(Name = "Dauer")]
        public int duration { get; set; }
        [Display(Name = "Bearbeitet von")]
        public AspNetUsers modifiedBy { get; set; }
        [Display(Name = "Bearbeitet am")]
        public DateTime modified { get; set; }
        [Display(Name = "Behandlungen")]
        public List<VisitTreatment> treatments { get; set; }

    }

    public class VisitCreateViewModel {
        [Key]
        public int visitId { get; set; }
        [Display(Name = "Datum")]
        public DateTime created { get; set; }
        [Display(Name = "Kunde")]
        public Customers customer { get; set; }
        [Display(Name = "Stylist")]
        public AspNetUsers stylist { get; set; }
        [Display(Name = "mögliche Behandlungen")]
        public List<Treatments> availableTreatments { get; set; }
        [Display(Name = "ausgewählte Behandlungen")]
        public List<Treatments> selectedTreatments { get; set; }

    }

    public class VisitTreatment {
        [Key]
        public int treatmentID { get; set; }
        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name = "Schritte")]
        public List<VisitTasks> tasks { get; set; }

        public VisitTreatment() {
            this.tasks = new List<VisitTasks>();
        }
    }
}

Salon/Models/Visits.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visits()
        {
            this.Pictures = new HashSet<Pictures>();
            this.VisitTasks = new HashSet<VisitTasks>();
        }
    
        public int VisitId { get; set; }
        public int Duration { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string TeacherId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual Customers Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pictures> Pictures { get; set; }
        public virtual Rooms Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitTasks> VisitTasks { get; set; }
    }
}

Salon/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Salon.Models;

namespace Salon.Controllers
{
    public class VisitsController : Controller
    {
        private SalonEntities db = new SalonEntities();

        // GET: Visits
        public ActionResult Index(int? skip)
        {                       
            if (skip == null || skip < 0)
                skip = 0;
            ViewBag.skip = skip;
            var visits = db.Visits.Include(v => v.AspNetUsers).Include(v => v.AspNetUsers1).Include(v => v.Customers);
            IEnumerable<VisitShortViewModel> shortVisitViewModels = (from v in visits
                                                                     orderby v.Created
                                                                     select new VisitShortViewModel {
                                                                         visitId = v.VisitId,
                                                                         created = v.Created,
                                                                         customer = v.Customers,
                                                                         stylist = v.AspNetUsers1
                                                                     }).Skip((int)skip * 30).Take(30).ToList();
            return View(shortVisitViewModels);
        }

        public ActionResult VisitShort() {
            var visits = db.Visits.Include(v => v.AspNetUsers).Include(v => v.AspNetUsers1).Include(v => v.Customers);
            IEnumerable<VisitShortViewModel> shortVisitViewModels = (from v in visits
                                                                     orderby v.Created
                                                                     select new VisitShortViewModel {
                                                                         visitId = v.VisitId,
                                                                         created = v.Created,
                                                                         customer = v.Customers,
                                                                         stylist = v.AspNetUsers1
                                                                     }).ToList();
            return View(shortVisitViewModels);
        }

        public ActionResult VisitDetails(int? id) {
            var visit = db.Visits.Find(id);
            VisitDetailViewModel visitDetails = new VisitDetailViewModel();
            visitDetails.visitId = visit.VisitId;
            visitDetails.created = visit.Created;
            visitDetails.customer = visit.Customers;
            visitDetails.stylist = visit.AspNetUsers1;
            visitDetails.modifiedBy = visit.AspNetUsers;
            visitDetails.modified = visit.Modified;
            visitDetails.duration = visit.Duration;
            visitDetails.treatments = getVisitTreatments(visit);
            
            return PartialView(visitDetails);
        }

        private List<VisitTreatment> getVisitTreatments(Visits v) {
            List<VisitTreatment> treatments = new List<VisitTreatment>();

            bool ok;
            foreach(VisitTasks vt in v.VisitTasks) {
                ok = false;
                foreach(VisitTreatment t in treatments) {
                    if(t.treatmentID == vt.TreatmentId) {
                        t.tasks.Add(vt);
                        ok = true;
                        break;
                    }
                }
                if (!ok) {
                    VisitTreatment visitTreatment = new VisitTreatment();
                    visitTreatment.treatmentID = vt.TreatmentId;
                    visitTreatment.name = vt.getTreatment().Title;
                    visitTreatment.tasks.Add(vt);
                    treatments.Add(visitTreatment);
                }
            }

            return treatments;
        }

        public ActionResult VisitCreate() {
            Models.Customers customer = db.Customers.Find(1);
            AspNetUsers stylist = db.AspNetUsers.Find("33abf8c7-5ae1-4ed6-819f-9d325e57d7bb");
      

            VisitCreateViewModel model = new VisitCreateViewModel();
            model.created = new DateTime();
            model.customer = customer;
            model.stylist = stylist;
            model.availableTreatments = db.Treatments.ToList();
            model.selectedTreatments = new List<Treatments>();
            return View(model);
        }

        // GET: Visits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visits visits = db.Visits.Find(id);
            if (visits == null)
            {
                return HttpNotFound();
            }
            return View(visits);
        }

        // GET: Visits/Create
        public ActionResult Create()
        {
            ViewBag.CreatedBy = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.ModifiedBy = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CountryId");
            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VisitId,Duration,CustomerId,ModifiedBy,Modified,CreatedBy,Created")] Visits visits)
        {
            if (ModelState.IsValid)
            {
                db.Visits.Add(visits);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CreatedBy = new SelectList(db.AspNetUsers, "Id", "Email", visits.CreatedBy);
            ViewBag.ModifiedBy = new SelectList(db.AspNetUsers, "Id", "Email", visits.ModifiedBy);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CountryId", visits.CustomerId);
            return View(visits);
        }

        // GET: Visits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visits visits = db.Visits.Find(id);
            if (visits == null)
            {
                return HttpNotFound();
            }
            ViewBag.CreatedBy = new SelectList(db.AspNetUsers, "Id", "Email", visits.CreatedBy);
            ViewBag.ModifiedBy = new SelectList(db.AspNetUsers, "Id", "Email", visits.ModifiedBy);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CountryId", visits.CustomerId);
            return View(visits);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VisitId,Duration,CustomerId,ModifiedBy,Modified,CreatedBy,Created")] Visits visits)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visits).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CreatedBy = new SelectList(db.AspNetUsers, "Id", "Email", visits.CreatedBy);
            ViewBag.ModifiedBy = new SelectList(db.AspNetUsers, "Id", "Email", visits.ModifiedBy);
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "CountryId", visits.CustomerId);
            return View(visits);
        }

        // GET: Visits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Visits visits = db.Visits.Find(id);
            if (visits == null)
            {
                return HttpNotFound();
            }
            return View(visits);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Visits visits = db.Visits.Find(id);
            db.Visits.Remove(visits);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Salon/Views/Visits/Create.cshtml
@model Salon.Models.Visits

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Visits</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, "ModifiedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModifiedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, "CreatedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CreatedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Salon/Views/Visits/Delete.cshtml
@model Salon.Models.Visits

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Visits</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers1.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers1.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customers.CountryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customers.CountryId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Salon/Views/Visits/Details.cshtml
@model Salon.Models.Visits

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Visits</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUsers1.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUsers1.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Customers.CountryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customers.CountryId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VisitId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Salon/Views/Visits/Edit.cshtml
@model Salon.Models.Visits

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Visits</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VisitId)

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, "CustomerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, "ModifiedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ModifiedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modified, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modified, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, "CreatedBy", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CreatedBy", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Salon/Views/Visits/Index.cshtml
@model IEnumerable<Salon.Models.VisitShortViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Besuche</h2>

<div class="row">
    <div class="col-sm-7">
        <div id="filterContainer">
            <div class="row">
                <div class="col-sm-3">
                    <label for="inp_filterDate">
                        @Html.DisplayNameFor(x => x.created)
                    </label>
                </div>
                <div class="col-sm-3">
                    <label for="inp_filterCustomer">
                        @Html.DisplayNameFor(x => x.customer)
                    </label>
                </div>
                <div class="col-sm-3">
                    <label for="inp_filterStylist">
                        @Html.DisplayNameFor(x => x.stylist)
                    </label>
                </div>
                <div class="col-sm-3">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <input type="text" id="inp_filterDate" class="form-control" />
                </div>
                <div class="col-sm-3">
                    <input type="text" id="inp_filterCustomer" class="form-control" />
                </div>
                <div class="col-sm-3">
                    <input type="text" id="inp_filterStylist" class="form-control" />
                </div>
                <div class="col-sm-3">
                    <button type="button" class="btn btn-primary" id="btn_filter">
                        <span class="glyphicon glyphicon-search"></span> Suche
                    </button>
                </div>
            </div>
        </div>
            
        <hr />
        <table class="table" id="tbl_visits">
            <tr>
                <th>
                    @Html.DisplayNameFor(x => x.created)
                </th>
                <th>
                    @Html.DisplayNameFor(x => x.customer)
                </th>
                <th>
                    @Html.DisplayNameFor(x => x.stylist)
                </th>
            </tr>
            @foreach (var item in Model) {
                <tr class="tr_visits" style="cursor: pointer;">
                    <td>
                        @item.created
                    </td>
                    <td>
                        @item.customer.FName @item.customer.LName
                    </td>
                    <td>
                        @if(item.stylist != null) {
                            @item.stylist.UserName
                        }
                        
                    </td>
                    <td>
                        @Html.ActionLink("Details", "VisitDetails", new { id = item.visitId }, new { @class = "visitRow" })
                    </td>
                </tr>
            }
        </table>
        <font id="fnt_hits">
            @Model.Count() Ergebniss(e)
        </font>
        <ul class="pager">
            @if (ViewBag.skip == 0) {
                <li class="disabled">
                    <a href="#">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                    </a>
                </li>
            } else {
                <li >
                    <a href="@Url.Action("Index", "Visits", new { skip = ViewBag.skip - 1 }) ">
                        <span class="glyphicon glyphicon-arrow-left"></span>
                    </a>
                </li>
            }
            <li>
                <a href="@Url.Action("Index", "Visits", new { skip = ViewBag.skip + 1 }) ">
                    <span class="glyphicon glyphicon-arrow-right"></span>
                </a>
            </li>
        </ul> 
    </div>
    <div class="col-sm-5" id="VisitTableContainer">

    </div>
</div>



@section scripts {
<script type="text/javascript">
    $(function() {
        $('.visitRow').on('click', function (e) {

            $.get($(this).prop('href'), function (response) {
                $('#VisitTableContainer').html(response)
            });
            e.preventDefault();
        });

        $(".tr_visits").each(function () {
            $(this).on('click', function (e) {
                
                $("#tbl_visits").find("tr").each(function (e) {
                    $(this).removeClass("active");
                });
                $(this).toggleClass("active");
                $.get($(this).find(".visitRow").prop('href'), function (response) {
                    $('#VisitTableContainer').html(response)
                });
                e.preventDefault();
            });
        });
    });

    
    $("#btn_filter").on('click', function (e) {
        filter();
    });




    /**
     * Visit Table Filter
     */
    function filter() {
        //get filter
        var fDate = $("#inp_filterDate").val();
        var fCustomer = $("#inp_filterCustomer").val();
        var fStylist = $("#inp_filterStylist").val();

        var table, tr, date, cust, styl;
        table = document.getElementById("tbl_visits");
        tr = table.getElementsByTagName("tr");

        var hitDate, hitCust, hitStyl, hits = 0;

        for (var i = 1; i < tr.length; i++) {       //loop through table rows
            date = tr[i].getElementsByTagName("td")[0];
            cust = tr[i].getElementsByTagName("td")[1];
            styl = tr[i].getElementsByTagName("td")[2];

            hitDate = false;
            hitCust = false;
            hitStyl = false;

            if (fDate.length > 0 && date.innerHTML.toUpperCase().indexOf(fDate.toUpperCase()) > -1) {
                hitDate = true;
            }
            if (fCustomer.length > 0 && cust.innerHTML.toUpperCase().indexOf(fCustomer.toUpperCase()) > -1) {
                hitCust = true;
            }
            if (fStylist.length > 0 && styl.innerHTML.toUpperCase().indexOf(fStylist.toUpperCase()) > -1) {
                hitStyl = true;
            }

            //check all filtered fields (if filter is empty check succeeds)
            if ((fDate.length == 0 || hitDate) && (fCustomer.length == 0 || hitCust) && (fStylist.length == 0 || hitStyl)) {
                tr[i].style.display = "";
                hits++;
            } else {
                tr[i].style.display = "none";
            }
        }
        $("#fnt_hits").html(hits + " Ergebnisse");
    }

</script>
}